services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: